import type { Agent, Task, Sprint, ActivityEntry, Escalation } from "./types";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-boss",
    name: "Boss",
    role: "boss",
    status: "working",
    color: "#F59E0B",
    current_task_id: null,
    avatar_label: "B",
  },
  {
    id: "agent-pm",
    name: "ProjectManager",
    role: "pm",
    status: "working",
    color: "#3B82F6",
    current_task_id: "task-2",
    avatar_label: "PM",
  },
  {
    id: "agent-sm",
    name: "ScrumMaster",
    role: "scrum_master",
    status: "idle",
    color: "#14B8A6",
    current_task_id: null,
    avatar_label: "SM",
  },
  {
    id: "agent-dev1",
    name: "Developer-1",
    role: "developer",
    status: "working",
    color: "#22C55E",
    current_task_id: "task-1",
    avatar_label: "D1",
  },
  {
    id: "agent-dev2",
    name: "Developer-2",
    role: "developer",
    status: "working",
    color: "#22C55E",
    current_task_id: "task-3",
    avatar_label: "D2",
  },
  {
    id: "agent-qa",
    name: "QA-Tester",
    role: "qa",
    status: "idle",
    color: "#F97316",
    current_task_id: null,
    avatar_label: "QA",
  },
  {
    id: "agent-cr",
    name: "CodeReviewer",
    role: "code_reviewer",
    status: "reviewing",
    color: "#8B5CF6",
    current_task_id: "task-4",
    avatar_label: "CR",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Implement user authentication",
    description: "Add JWT-based auth with login/register endpoints",
    status: "in_progress",
    priority: "P0",
    assigned_agent_id: "agent-dev1",
    assigned_agent_name: "Developer-1",
    assigned_agent_color: "#22C55E",
    sprint_id: "sprint-1",
    created_at: "2026-03-01T08:00:00Z",
    updated_at: "2026-03-01T10:30:00Z",
  },
  {
    id: "task-2",
    title: "Design database schema",
    description: "Create PostgreSQL schema for users, tasks, and sprints",
    status: "in_progress",
    priority: "P0",
    assigned_agent_id: "agent-pm",
    assigned_agent_name: "ProjectManager",
    assigned_agent_color: "#3B82F6",
    sprint_id: "sprint-1",
    created_at: "2026-03-01T08:00:00Z",
    updated_at: "2026-03-01T09:15:00Z",
  },
  {
    id: "task-3",
    title: "Build REST API endpoints",
    description: "Create CRUD endpoints for task management",
    status: "in_progress",
    priority: "P1",
    assigned_agent_id: "agent-dev2",
    assigned_agent_name: "Developer-2",
    assigned_agent_color: "#22C55E",
    sprint_id: "sprint-1",
    created_at: "2026-03-01T08:30:00Z",
    updated_at: "2026-03-01T11:00:00Z",
  },
  {
    id: "task-4",
    title: "Code review: Auth module",
    description: "Review authentication implementation for security issues",
    status: "review",
    priority: "P1",
    assigned_agent_id: "agent-cr",
    assigned_agent_name: "CodeReviewer",
    assigned_agent_color: "#8B5CF6",
    sprint_id: "sprint-1",
    created_at: "2026-03-01T09:00:00Z",
    updated_at: "2026-03-01T12:00:00Z",
  },
  {
    id: "task-5",
    title: "Write unit tests for API",
    description: "Add pytest tests for all REST endpoints",
    status: "backlog",
    priority: "P1",
    assigned_agent_id: null,
    assigned_agent_name: null,
    assigned_agent_color: null,
    sprint_id: "sprint-1",
    created_at: "2026-03-01T08:00:00Z",
    updated_at: "2026-03-01T08:00:00Z",
  },
  {
    id: "task-6",
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated testing and deployment",
    status: "backlog",
    priority: "P2",
    assigned_agent_id: null,
    assigned_agent_name: null,
    assigned_agent_color: null,
    sprint_id: "sprint-1",
    created_at: "2026-03-01T08:00:00Z",
    updated_at: "2026-03-01T08:00:00Z",
  },
  {
    id: "task-7",
    title: "Add input validation",
    description: "Implement Pydantic validation on all request bodies",
    status: "done",
    priority: "P0",
    assigned_agent_id: "agent-dev1",
    assigned_agent_name: "Developer-1",
    assigned_agent_color: "#22C55E",
    sprint_id: "sprint-1",
    created_at: "2026-03-01T07:00:00Z",
    updated_at: "2026-03-01T09:00:00Z",
  },
  {
    id: "task-8",
    title: "Configure logging",
    description: "Set up structured logging with correlation IDs",
    status: "done",
    priority: "P2",
    assigned_agent_id: "agent-dev2",
    assigned_agent_name: "Developer-2",
    assigned_agent_color: "#22C55E",
    sprint_id: "sprint-1",
    created_at: "2026-03-01T07:30:00Z",
    updated_at: "2026-03-01T08:45:00Z",
  },
];

export const MOCK_SPRINT: Sprint = {
  id: "sprint-1",
  name: "Sprint 1 - Foundation",
  status: "active",
  total_tasks: 8,
  completed_tasks: 2,
  start_date: "2026-03-01T00:00:00Z",
  end_date: "2026-03-14T00:00:00Z",
};

export const MOCK_ACTIVITIES: ActivityEntry[] = [
  {
    id: "act-1",
    timestamp: "2026-03-01T12:01:00Z",
    agent_id: "agent-boss",
    agent_name: "Boss",
    agent_color: "#F59E0B",
    message: "Sprint 1 kickoff complete. Assigning tasks to agents.",
    type: "info",
  },
  {
    id: "act-2",
    timestamp: "2026-03-01T12:02:30Z",
    agent_id: "agent-pm",
    agent_name: "ProjectManager",
    agent_color: "#3B82F6",
    message: "Database schema design started. Using PostgreSQL with 4 main tables.",
    type: "info",
  },
  {
    id: "act-3",
    timestamp: "2026-03-01T12:05:00Z",
    agent_id: "agent-dev1",
    agent_name: "Developer-1",
    agent_color: "#22C55E",
    message: "Completed input validation task. Moving to auth implementation.",
    type: "success",
  },
  {
    id: "act-4",
    timestamp: "2026-03-01T12:08:00Z",
    agent_id: "agent-dev2",
    agent_name: "Developer-2",
    agent_color: "#22C55E",
    message: "REST API endpoints in progress. 3/7 endpoints complete.",
    type: "info",
  },
  {
    id: "act-5",
    timestamp: "2026-03-01T12:10:00Z",
    agent_id: "agent-cr",
    agent_name: "CodeReviewer",
    agent_color: "#8B5CF6",
    message: "Reviewing auth module. Found potential SQL injection vector.",
    type: "warning",
  },
  {
    id: "act-6",
    timestamp: "2026-03-01T12:12:00Z",
    agent_id: "agent-boss",
    agent_name: "Boss",
    agent_color: "#F59E0B",
    message: "Escalation: Security concern in auth module needs human review.",
    type: "error",
  },
  {
    id: "act-7",
    timestamp: "2026-03-01T12:15:00Z",
    agent_id: "agent-sm",
    agent_name: "ScrumMaster",
    agent_color: "#14B8A6",
    message: "Sprint velocity on track. 2/8 tasks done, 3 in progress.",
    type: "info",
  },
];

export const MOCK_ESCALATION: Escalation = {
  id: "esc-1",
  title: "Security Vulnerability in Auth Module",
  description:
    "CodeReviewer found a potential SQL injection vulnerability in the authentication module. The user input is not properly sanitized before database queries.",
  recommendation:
    "Recommend using parameterized queries and adding input sanitization middleware. Developer-1 should fix before proceeding with other auth work.",
  agent_id: "agent-boss",
  agent_name: "Boss",
  severity: "high",
  status: "pending",
  created_at: "2026-03-01T12:12:00Z",
};
